name: standard checks

on:
    push:
        branches:
            - main
    workflow_dispatch:
    pull_request:
        types: [opened, edited, synchronize]

env:
    HUSKY: 0

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "npm"
            - run: npm ci
            - run: npm run lint -- --deny-warnings

    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "npm"
            - run: npm ci
            - run: npm run pretty

    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "npm"
            - run: npm ci
            - run: npm audit --omit=dev

    e2e-tests:
        needs: [lint, prettier, audit]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "npm"
            - name: Cypress run
              uses: cypress-io/github-action@v7
              with:
                  start: |
                      npm run dev
                  #   wait-on: 'http://localhost:8000'
                  #   wait-on-timeout: 60
                  #   browser: chrome
